name: Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: NVM use
      uses: dcodeIO/setup-node-nvm@master

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint

    - name: Prettier
      run: yarn prettier:check

    - name: Build
      run: yarn clean && yarn build

    - name: Package & Publish
      env:
        APPLEID: ${{ secrets.APPLEID }}
        APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        CSC_LINK: ${{ secrets.CSC_LINK }}
      run: yarn package-and-publish
